### ISSUE TITLE
Edit CSS code

### ISSUE THREAD

**Issue by ikubiti** [ikubiti/password-generator#4]
# Edit CSS Code

## User Story

As a potential web developer keen to acquire technical competence
I want to develop CSS code that is clean and polished
So that all user agents can present a user interface that is responsive and adapts to multiple screen sizes

## Acceptance Criteria

Given I need to have a responsive page
When I view the CSS code
Then I see elements that follow the HTML semantic structure
When I read the CSS code
Then I find it readable with appropriate comments

**Comment by umrian** [comment]
### I tried my best with responsiveness and color harmony without losing track of your primary color palettes.
`/* Setting up variables for ease of future maintainance */
:root {
  --body-color: hsl(204, 45%, 98%);
  --accent-color: hsl(360, 91%, 36%);
  --text-color: hsl(206, 17%, 20%);
}

/* For browsers default dark theme */
@media (prefers-color-scheme: dark) {
  :root {
    --body-color: hsl(0, 0%, 10%);
    --accent-color: hsl(360, 81%, 50%);
    --text-color: hsl(206, 17%, 58%);
  }
}
/* Modern Css reset by Paccalilli */
/* Box sizing rules */
*,
*::before,
*::after {
  box-sizing: border-box;
}

/* Remove default margin */
body,
h1,
h2,
h3,
h4,
p,
figure,
blockquote,
dl,
dd {
  margin: 0;
}

/* Set core root defaults */
html:focus-within {
  scroll-behavior: smooth;
}

/* Set core body defaults */
body {
  min-height: 100vh;
  text-rendering: optimizeSpeed;
  line-height: 1.5;
  font-family: Arial, Helvetica, sans-serif;
  background-color: var(--body-color);
}

/* Make images easier to work with */
img,
picture {
  max-width: 100%;
  display: block;
}

/* Inherit fonts for inputs and buttons */
input,
button,
textarea,
select {
  font: inherit;
}

/* Main Style starts here */
.wrapper {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-block: 2rem;
}

header {
  margin-block: 1.2rem;
  text-align: center;
  font-size: clamp(0.8rem, -0.875rem + 4.333vw, 1.1rem);
  color: var(--accent-color);
}

.card {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-inline: 2rem;
  padding-block: 1.8rem;
  width: 90%;
  max-width: 70rem;
  font-size: clamp(0.4rem, 4vw, 1.75rem);
  color: var(--text-color);
  background-color: hsl(0, 0%, 100%);
  border-radius: 5px;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}

.card-header::after {
  content: " ";
  display: block;
  width: calc(100% - 6vw);
  margin-inline: auto;
  background: var(--accent-color);
  opacity: 0.8;
  height: 2px;
}

.card-body {
  min-height: 100px;
  width: 100%;
  max-width: 40rem;
}

#password {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  display: block;
  font-size: 1.5rem;
  text-align: center;
  padding-top: 1em;
  padding-inline: 1em;
  padding-bottom: 5em;
  margin-block: 1em;
  width: 100%;
  border: 2px dashed #c0c7cf;
  border-radius: 6px;
  resize: none;
  overflow: hidden;
}

textarea:focus {
  outline: 2px dashed var(--accent-color);
}

.card-footer::after {
  content: " ";
  display: block;
  clear: both;
}

.btn {
  display: inline-block;
  font-size: 22px;
  color: var(--body-color);
  line-height: 22px;
  text-align: center;
  padding: 14px 34px;
  margin: 16px 16px 16px 20px;
  cursor: pointer;
  background-color: var(--accent-color);
  border: none;
  border-radius: 25px;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 6px 0px rgba(0, 0, 0, 0.2) 0px 1px 1px
    0px;
}

.btn:focus,
.btn:hover {
  color: var(--body-color);
  background-color: var(--accent-color);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}

.btn:focus {
  outline: 2px solid var(--accent-color);
  outline-offset: 1.5px;
}

button[disabled] {
  cursor: default;
  background: #c0c7cf;
}

@media (max-width: 43em) {
  .btn {
    font-size: 1rem;
    margin: 1em 0 0 0;
    padding: 0.6em 1em;
  }
}

@media (max-width: 31em) {
  .btn {
    font-size: 1rem;
  }
}

.float-right {
  float: right;
}
`

**Comment by ikubiti** [comment]
Added semantic HTML elements to CSS code and improved the application's responsiveness.
